language: ruby
rvm: 2.2
install: bundle exec jekyll serve
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master # Or `gh-pages`